{% set name = "pyembree" %}
{% set org = "scopatz" %}
{% set version = "0.1.6" %}
{% set sha256 = "d16823a8886c9e8e8c451243460ccde7e659dac78e1ddfae7110895dae324777" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win or armv6l or armv7l or ppc64le or aarch64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=51.0.0
    - cython >=0.29.24,<3
    - numpy
    - embree
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - embree

test:
  imports:
    - pyembree
  commands:

about:
  home: https://github.com/scopatz/pyembree
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python Wrapper for Embree'
  dev_url: https://github.com/scopatz/pyembree

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
    - ocefpaf
    - dsuess
