{% set name = "pyembree" %}
{% set org = "scopatz" %}
{% set version = "0.1.3" %}
{% set sha256 = "c8c8d138d4910e42bd2fe16977ca0a1dd8d1ec7d4f13b535a38f70ac97026aa7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - cython >=0.25.2
    - numpy 1.11.*
    - embree
  run:
    - python
    - numpy >=1.11
    - embree

test:
  imports:
    - pyembree
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/scopatz/pyembree
  license: BSD 2-clause
  license_file: LICENSE
  summary: 'Python Wrapper for Embree'
  dev_url: https://github.com/scopatz/pyembree

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
    - ocefpaf
